### ISSUE TITLE
Feature to answer with Project suggestions

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#101]
## Description
As a developer,
I need to add a feature,
so that the bot can respond to messages from newcomers on #intro channel with project suggestions.

## Mocks
-N.A.-

### Update [Required]
- [ ] The bot will check for languages mentioned in the introductory message and reply with project suggestions.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by sammy1997** [comment]
@ramitsawhney27 @sara-02 Issue as per deliverables.

**Comment by sara-02** [comment]
@sammy1997 Go ahead. I hope whatever code we put, we can extend it to a few other channels like `questions` and `newcomers` as well. People sometimes ask these project suggestion questions there as well.
