### ISSUE TITLE
Unit testing to cover 90%

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#106]
## Description
As a developer,
I need to add unit tests,
so that I can cover 90% of the code.

## Mocks
-N.A.-

### Update [Required]
- [ ] Added the test to reach 90% code coverage 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

**Comment by GeVic** [comment]
@sammy1997 Can I work on this?

**Comment by sammy1997** [comment]
Sorry @GeVic This is a GSoC requirement. You can though work after I complete 90%. You can take it higher.
