### ISSUE TITLE
Minor Patches for AWS and answering feature

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#112]
## Description
As a developer,
I need send a patch,
so that I can remove some errors related to AWS auto-deployment and answer feature.

## Mocks
-N.A.-

### Update [Required]
- [ ] Change settings for Auto-Deployment( as discussed with Murad) so that AWS deployment works when the code is merged
- [ ] Fix the answering feature

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by sara-02** [comment]
@sammy1997 sure, go ahead, approving it.

**Comment by sammy1997** [comment]
@sara-02 You can use the bot command as well. It's functional for this repo :)

**Comment by sara-02** [comment]
Ah, ok, I will remember it for the next time :grin:
