### ISSUE TITLE
Add Pythonic docstrings: Improve docstring coverage

### ISSUE THREAD

**Issue by sara-02** [systers/sysbot#115]
## Description
As a contributor/new-comer,
I would require doc-strings support for the implemented functions and classes.
so that I can understand the functions easily.

## Mocks
The best way is to follow the Python's PEP8 Docstring convention.
More details here: https://www.python.org/dev/peps/pep-0257/

### Update [Required]
- [ ] Add doc-strings to the functions and classes.
- [ ] Main server.py where it is missing.
- [ ] .py files in the `Code folder` where it is missing.
- [ ] .py files in the `Test folder` where it is missing.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2-3 hours

**Comment by sara-02** [comment]
@sammy what did I miss in the template :/

**Comment by ramitsawhney27** [comment]
@sys-bot approve

**Comment by sammy1997** [comment]
@sara-02 Same as the doc issue, the check expects Update header to be below Acceptance criteria, and no text.

**Comment by sammy1997** [comment]
Why is this labelled invalid? @sara-02

**Comment by sara-02** [comment]
Oh, it was a mistake.

**Comment by sammy1997** [comment]
Sure @GeVic ! Please get invited into the newcomers team from Slack and claim this issue.

**Comment by GeVic** [comment]
@sys-bot claim
