### ISSUE TITLE
Unit testing to cover 60%

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#118]
## Description
As a developer,
I need to add unit tests,
so that I can cover 60% of the code.

## Mocks
-N.A.-

### Update [Required]
- [ ] Added the test to reach 60% code coverage 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by sara-02** [comment]
@sys-bot approve
