### ISSUE TITLE
systers/mentorship-backend is not showing on the python projects response on Slack

### ISSUE THREAD

**Issue by isabelcosta** [systers/sysbot#119]
## Description
As a member of Systers Open Source,
I need be able to know what are the projects and the corresponding tech stack,
so that I can learn about the existing projects I can contribute to.

The [systers/mentorship-backend](https://github.com/systers/mentorship-backend) is not showing when a contributor asks for projects that use Python.

## Mocks

![image](https://user-images.githubusercontent.com/11148726/43258483-de41f702-90ca-11e8-8051-c278f4d45e1a.png)

### Update [Required]
- [ ] Add [systers/mentorship-backend](https://github.com/systers/mentorship-backend) repository to the python projects response on Slack.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by sammy1997** [comment]
@sys-bot approve

**Comment by sammy1997** [comment]
@sys-bot claim

**Comment by sammy1997** [comment]
As it turns out, the issue was solved in code but wasn't updated on the server!

![python_repos](https://user-images.githubusercontent.com/24635701/43260223-6d2ed2ca-90f6-11e8-841d-e510b7d70349.png)

Now it's fixed so closing this issue. Thanks @isabelcosta
