### ISSUE TITLE
Create a environment requirements file

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#12]
## Description
As a developer,
I need to create a reqirements.txt file,
so that a virtual environment can be created.

### Update [Required]
- [ ] Create a requirements.txt file

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 mins

**Comment by sammy1997** [comment]
@ramitsawhney27 @Akshitaag @prachi1210 Please review this.

**Comment by Akshitaag** [comment]
You can start working on this. @sammy1997
