### ISSUE TITLE
Commands on README.md are not highlighted as code

### ISSUE THREAD

**Issue by isabelcosta** [systers/sysbot#120]
## Description
As a newcomer,
I need see the commands by Sysbot highlighted on the README.md file,
so that I can read better and get a clear idea of the commands syntax.

[README.md](https://github.com/systers/sysbot/blob/develop/docs/README.md) file has the syntax of the Sysbot commands like normal text.

**Current:** Similarly, maintainers and collaborators can assign an issue to a member by the comment '@sys-bot assign <assignee_github_username>'

**Suggestion:** Similarly, maintainers and collaborators can assign an issue to a member by the comment `@sys-bot assign <assignee_github_username>`

## Mocks

![image](https://user-images.githubusercontent.com/11148726/43259241-60b88938-90cd-11e8-9bdc-8b33182291c9.png)

### Update [Required]
- [ ] Update README.md with code like syntax on Sysbot commands

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by isabelcosta** [comment]
I thought this could be assigned to a newcomer, unless its something that is soon going to be changed for GSoC. Is this issue valid? @systers/maintainers-sysbot @sammy1997

**Comment by yatri1609** [comment]
@sammy1997 Can I work on this issue?

**Comment by sammy1997** [comment]
Sure @yatri1609

**Comment by sammy1997** [comment]
@sys-bot assign yatri1609

**Comment by yatri1609** [comment]
Thanks I'll work on it. @sammy1997
