### ISSUE TITLE
Issue was not assigned Not Approved label once created bug

### ISSUE THREAD

**Issue by isabelcosta** [systers/sysbot#123]
## Description
As a maintaines,
I need to @sys-bot to assign `Not Approved` label to newly created issues,
so that I can avoid new members to start working on issues before a maintainer approving the issue.

@sys-bot did not put `Not Approved` label into new issue created on [systers/mentorship-backend](https://github.com/systers/mentorship-backend) repository
Issues where this happened: https://github.com/systers/mentorship-backend/issues/117
The Sysbot tends to answer right away

**How I created the issue:**
1. Wrote the description and title
2. Added labels to the issue
3. Assigned myself to the issue
4. Submitted the issue (clicked "Submit new issue" button)

**Other Info:**
- I have write access to the repository
- Time of creation: 12:29 AM GMT +1

## Mocks

![image](https://user-images.githubusercontent.com/11148726/43294068-7b6c1070-9135-11e8-9410-89b65aec6c7d.png)

### Update [Required]
- [ ] Investigate and fix Sysbot to work with all of the issues (if needed)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by sammy1997** [comment]
@isabelcosta I guess that was some one-time anomaly! I checked the logs and the server didn't receive the event at all! As you can see, even this issue got labelled quite fine! And so did the other issues in Sysbot and mentorship-backend! I am keeping this issue open, if you see the same happen for 2-3 times do comment it here!

**Comment by sammy1997** [comment]
@isabelcosta If you haven't found the same bug again, I am closing this. What say?

**Comment by isabelcosta** [comment]
Ok! I haven't created more issues on backend, since I'm focused on Android now. sur you can close it @sammy1997

**Comment by sara-02** [comment]
Thanks @isabelcosta

**Comment by sara-02** [comment]
Feel free to reopen this, if you come across it again.
