### ISSUE TITLE
Collect data for each event for event mocking

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#126]
## Description
As a developer,
I need to add data,
so that I can perform the Slack and Github event Simulation.

## Mocks
-N.A.-

### Update [Required]
- [ ] PR should have either a json or .py file with data for each event to be simulated

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by sara-02** [comment]
@sys-bot approve
