### ISSUE TITLE
Add command to change PR labels from not-reviewed to reviewed

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#127]
## Description
As a developer,
I need to add a feature to Sysbot,
so that the bot can change PR review labels when a review is sent.

## Mocks
-N.A.-

### Update [Required]
- [ ] Add feature to bot

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by sara-02** [comment]
@sys-bot  approve

**Comment by sara-02** [comment]
@sys-bot approve

**Comment by sammy1997** [comment]
@sys-bot approve

**Comment by sara-02** [comment]
@sys-bot approve

**Comment by GeVic** [comment]
@sara-02 Although I saw the GSoC label, but still I would ask to work on the same.

**Comment by sammy1997** [comment]
@GeVic It's a part of discussed deliverables for me. I think you will have to look at the non-GSoC issues.
