### ISSUE TITLE
[Enhancement] Label list feature

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#129]
## Description
As a developer,
I need to add a feature,
so that a user can command the bot to label an issue with a list of comma-seperated labels.

## Mocks
-N.A.-

### Update [Required]
- [ ] Create a sys-bot label command

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by sara-02** [comment]
@sys-bot approve

**Comment by sammy1997** [comment]
@sys-bot claim
