### ISSUE TITLE
Mocking events for Slack and Github

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#132]
## Description
As a developer,
I need to add a script,
so that I developers can locally manage event delivery.

## Mocks
-N.A.-

### Update [Required]
- [ ] Add script to mock event delivery for local deveopment

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by ramitsawhney27** [comment]
@sys-bot approve
