### ISSUE TITLE
Put a check on overlapping languages( if one is contained in another)

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#133]
## Description
As a developer,
I need to put a check on overlapping languages, like Java and Javascript

## Mocks
![issue_bug](https://user-images.githubusercontent.com/24635701/43479833-094a6f26-951f-11e8-968c-b55983a69f24.png)

### Update [Required]
- [ ] Fix the bug

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by ramitsawhney27** [comment]
@sys-bot approve
