### ISSUE TITLE
Update documentation with newly added enhancements

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#139]
## Description
As a developer,
I need to update the documentation,
so that all the new features are included.

## Mocks
-N.A.-

### Update [Required]
- [ ] Update documentation with information about new features 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by ramitsawhney27** [comment]
sys-bot approve

**Comment by sara-02** [comment]
@sys-bot approve
