### ISSUE TITLE
View issue on Slack

### ISSUE THREAD

**Issue by ramitsawhney27** [systers/sysbot#141]
## Description
As a user
I need to be able to view an issue directly on slack
so that I can handle an issue directly via slack.

### Update [Required]
- [ ] Adding a functionality view-issue that directly sends the user the issue (description and update). 
### Enhancement to Update [Optional]
- [ ] Parse markdown in the github issue and have some sort of formatting when sent to the user on Slack.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by sara-02** [comment]
@sys-bot approve
