### ISSUE TITLE
Fix AWS auto-deployment

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#143]
## Description
As a developer,
I need to add doc string test command and fix AWS auto-deployment.

## Mocks
-N.A.-

### Update [Required]
- [ ] Fix AWS auto-deployment.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hour

**Comment by sammy1997** [comment]
@sara-02 @ramitsawhney27 I please approve this issue!

**Comment by sara-02** [comment]
@sysbot approve

**Comment by sara-02** [comment]
@sys-bot approve

**Comment by sara-02** [comment]
@sammy1997, @GeVic is working on adding doc-strings, maybe you can coordinate with him
