### ISSUE TITLE
Encrypt tokens/keys and post the encrypted keys to prevent disabling of tokens by Slack

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#145]
## Description
As a developer,
I need to encrypt the test tokens,
so that it can be shared on GitHub without them getting revoked.

## Mocks
![slack_info](https://user-images.githubusercontent.com/24635701/43768240-87cf5f7a-9a54-11e8-823a-ee4febcad64f.png)

### Update [Required]
- [ ] Provide a file and update documentation with encrypted keys

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by sammy1997** [comment]
@sara-02 @ramitsawhney27 Please review this

**Comment by sara-02** [comment]
@sys-bot approve

**Comment by sara-02** [comment]
@sammy1997 Can you give an overview of your solution here, before sending the PR :)

**Comment by sammy1997** [comment]
@sara-02 I am using codecs library provided by python to encode the keys. I will pass these keys as parameters to the decoder functions, which will decode it and print it in the terminal when a script is run. That way the tokens won't directly get posted online, and others can get it on their local machines

**Comment by sara-02** [comment]
@sammy1997 Got it.
