### ISSUE TITLE
Create a new test_dictionary set for channel IDs of Sample workspace

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#147]
## Description
As a developer,
I need to create another test_dictionary file same as the dictionary,
so that it contains channel IDs of the test workspace/ sample workspace.

## Mocks
-NA.-

### Update [Required]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by sara-02** [comment]
@sys-bot approve
