### ISSUE TITLE
[Enhancement] Add a Slack command corresponding to issue/PR labelling Github feature

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#149]
## Description
As a developer,
I need to add a Slash command on Slack,
so that users can label an issue with multiple labels directly from SLack.

## Mocks
-N.A.-

### Update [Required]
- [ ] Add a slash command on Slack for labelling issues with multiple labels directly from Slack

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by sara-02** [comment]
@sys-bot approve
