### ISSUE TITLE
Create a file for keeping the messages and comments that will be made by the bot

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#15]
## Description
As a developer,
I need to create a separate messages file,
so that I can keep the main code clean.

## Mocks
-N.A-

### Update [Required]
- [ ] Add a message.py file with all the messages/comments that will be made by the bot

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 mins

**Comment by sara-02** [comment]
@sammy1997 Will this only contain `key values`, like a config file. Or will it contain code snippets as well? I suggest to keep a key-value file of messages, eg: `Welcome_message:"hello"`. And then use the key in the code where it is needed.

**Comment by ramitsawhney27** [comment]
Approved. please send a PR.
