### ISSUE TITLE
Merge GSoC18 work to master

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#159]
## Description
As a GSoC Student,
I need to merge all the work done during GSOC,
from develop to master branch.

## Mocks
-N.A.-

### Update [Required]
- [ ] Merge all code and solve any error or conflicts

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by sara-02** [comment]
@sys-bot I approving this issue

**Comment by sara-02** [comment]
@sys-bot  assign @sammy1997

**Comment by sara-02** [comment]
@sys-bot  help

**Comment by sara-02** [comment]
Fixed in #163 and #164
