### ISSUE TITLE
Include repositories names in PR reviews status message on Slack

### ISSUE THREAD

**Issue by isabelcosta** [systers/sysbot#166]
## Description
As a member of Systers Open Source Slack,
I need to get proper Sysbot messages regarding the PR reviews left to be reviewed,
so that I can understand to what repository the message is referring to.

**What happened:** Sysbot sent 2 messages to the #mentorship-system channel on Systers Open Source Slack, regarding the state of PR reviews. These two messages were the same which seemed confusing at first and seemed almost like an erratic behavior, but as @sammy1997 pointed out it must because Mentorship System has two repositories.

**My suggestion:** Show explicitly in the message, which repo the status message is referring to.
- Instead of: `All PR reviews up to date. None pending.`
- Show: `All PR reviews from systers/mentorship-backend repository is up to date. None pending.`

## Mocks

Duplicate message on Slack

![image](https://user-images.githubusercontent.com/11148726/44286801-5583dd00-a262-11e8-9d0e-2993e1555de6.png)

### Update [Required]
- [ ] Change PR reviews status message of Sysbot to include the name of the repository 

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

**Comment by anshulahuja98** [comment]
can i work on this, although i might end up taking a bit longer because setting up the project seems like a long task

**Comment by sara-02** [comment]
@anshulahuja98 Since you have asked to work on multiple issues, I would say pick one, and once you are decided let me know, I will assign you that issue.

**Comment by sammy1997** [comment]
@anshulahuja98 You should work on one issue ideally! As you have commented on many issues, do decide which one you want to work on and then you can work on that!

**Comment by anshulahuja98** [comment]
@sara-02 @sammy1997  thanks for the reply, i am sorry if it seemed inappropriate to comment on multiple issues, I am new to contributing to open projects. I thought that I might not get response on my comments, hence I commented on multiple issues that interested me.

I'm setting up the project, I will let you know the issue I would be working on.

**Comment by isabelcosta** [comment]
@anshulahuja98 are you a part of Systers Open Source slack community? You can get a lot of your doubts about open source with this community there :)

**Comment by anshulahuja98** [comment]
@isabelcosta no, i was not able to find a working link to join slack. There was some page to get an invite, but it didn't work

**Comment by isabelcosta** [comment]
@anshulahuja98 Oh I get that, I checked the link and is not working, I will report that and get back to you

**Comment by isabelcosta** [comment]
@anshulahuja98 here's the link you can use https://slack-systers-opensource.herokuapp.com/ soon it will be linked to the systers.io website

**Comment by anshulahuja98** [comment]
i registered using this, didn't receive an invite

**Comment by isabelcosta** [comment]
@anshulahuja98 for your GitHub primary email? That must be the email. Have you registered before?

**Comment by anshulahuja98** [comment]
I used the correct email ID, I'm sure of that, it also showed the success page to check email. I haven't registered before, but I obviously have a slack account associated with my email

**Comment by isabelcosta** [comment]
@anshulahuja98 I have no idea of what might be happening :O

**Comment by anshulahuja98** [comment]
@sara-02  can you please assign this issue to me?

**Comment by anshulahuja98** [comment]
I have made the appropriate code changes, just waiting for you to assign it, so that i can send a PR 👍
