### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by aayushinigam** [systers/sysbot#167]
## Description
As a contributor,
I need to know that I should first export all the environment variables  before running `main_server.py` ,
so that I don't get errors.

### Update [Required]
- [ ] Update Readme to direct the contributor to visit https://github.com/systers/sysbot/blob/develop/docs/exporting_keys.md 
before running `main_server.py`
- [ ] Create an `env.template` (for environment variables) and provide its link in Readme (see comments below for reference)
- [ ] Add a point in Readme which directs the contributor to fetch the latest code from branch `develop`.
 
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by anshulahuja98** [comment]
can i work on this?

**Comment by sara-02** [comment]
@aayushinigam It will not a good idea to mention all the `env variables` in the readme, but we can have an env.template and link that in the readme instead. What do you think will be easier for newcomers?

**Comment by aayushinigam** [comment]
Oh yes that's a better idea. It will be easier.

**Comment by sara-02** [comment]
Can you update the issue, and then I can approve it :)

**Comment by aayushinigam** [comment]
Also, there are various branches. Can we also include a point in Readme where we could ask the contributor to fetch the latest code from `develop` ?

**Comment by isabelcosta** [comment]
I like that idea as well I will suggest this for Mentorship System

**Comment by aayushinigam** [comment]
@sara-02 Please approve.

**Comment by aayushinigam** [comment]
Ah this is a bug!

**Comment by sara-02** [comment]
@aayushinigam No, it is deliberately added so that the author of the issue cannot approve it, because once an issue is approved it can be claimed an assigned.

**Comment by sara-02** [comment]
@sys-bot approve

**Comment by sara-02** [comment]
@aayushinigam do you want this to be assigned to you?

**Comment by aayushinigam** [comment]
@sara-02 No I'm not talking about that. I wasn't approving it myself. I asked you to approve it, so technically sysbot shouldn't comment.
And yes please assign it to me.

**Comment by sammy1997** [comment]
@anshulahuja98 I think @aayushinigam has asked to work on this before, so if she wants she should get this.

**Comment by sammy1997** [comment]
@aayushinigam Try to claim it....I guess you should be able to claim

**Comment by aayushinigam** [comment]
@sys-bot claim

**Comment by sammy1997** [comment]
@sara-02 I think the versatile issue approval should be removed unless an ML alternative is found....It's giving the bug

**Comment by sammy1997** [comment]
See this above one for instance

**Comment by sammy1997** [comment]
@aayushinigam Did you put any extra spaces or something in between? I used the API to test your assignment, and it worked

**Comment by sammy1997** [comment]
Can you try claiming again @aayushinigam ?

**Comment by aayushinigam** [comment]
@sys-bot claim

**Comment by sara-02** [comment]
@sammy1997 @aayushinigam I see now, what you guys are talking about. @aayushinigam Please file a bug for this, and yes, let us take the issue versatility part down for the moment and keep the approval in fix format.

**Comment by sammy1997** [comment]
@aayushinigam ca include another change into this doc itself? To add the export instructions for BOT_UID.
You can see the Slack discussions. I have provided the UID of the bot in the sample-workspace there.
