### ISSUE TITLE
PEP8  fix in /tests

### ISSUE THREAD

**Issue by anshulahuja98** [systers/sysbot#169]
## Description
As a member,
I need fix .py files in /tests
so that I can comply with PEP8 standards

## Mocks
tests/test_slack_functions.py:55:42: E225 missing whitespace around operator
tests/test_slack_functions.py:80:48: E225 missing whitespace around operator
tests/test_github_functions.py:2:1: F401 'list_open_prs_from_repo' imported but unused
tests/test_main_server.py:88:50: E225 missing whitespace around operator

### Update [Required]
- [ ] fix PEP8 errors
- [ ] add flake8 to travis

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by anshulahuja98** [comment]
can you please approve this and assign it to me?

**Comment by ramitsawhney27** [comment]
I don’t see the point in having a separate PR and issue for 5 minor breaches of PEP8. We’ll get that sorted with the next PR that actually fixes a functionality or bug. There’s automatic tools that can fix this too.
