### ISSUE TITLE
Inclusion of stemming to check phrases.

### ISSUE THREAD

**Issue by ramitsawhney27** [systers/sysbot#17]
## Description
As a user,
I need stem each of the user sentences when interacting with sysbot and then match with the created text files,
so that I can handle a vast variety of sentence variations with little computational effort.

### Update [Required]
- [ ] Add a simple function using NLTK PorterStemmer that takes as an input a string, stems the string and returns the stemmed version of the string.
- [ ] This returned string will later be used to match substrings of the text file. A separate issue will be created for this.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by sara-02** [comment]
@ramitsawhney27 one issue that we are bound to face is that it will not perform well for developer-centric terms/sentences. Since these stemmers are trained on English data. But it is good to start with +1 on that.

**Comment by ramitsawhney27** [comment]
@sara-02 yes. There’s a very vast variety of problems that need to be solved. Given that we want to focus more on creating the basic functionality of Sysbot as a priority, all such improvements come under enhancements. This can range from adding more nltk computations like Named entity recognition and POS tagging upto a full-fledged sentence classifier. We can discuss more of this in the future in community sessions as well! We’ll be working on enhancements too, just at a lower priority over the bot’s basic functionality is complete. I’m really happy to get more opinions on this, thankyou!

**Comment by sammy1997** [comment]
@ramitsawhney27 After reading about I have got this - the [portal2 in stemming](https://pypi.org/project/stemming/1.0/#description) library is currently as good as stemming algos get. So I will be using that for now. Views on this ?
