### ISSUE TITLE
code/dictionaries.py: Triple quoted string literal not closed

### ISSUE THREAD

**Issue by bhawesh96** [systers/sysbot#174]
## Description
As a developer,
I need to fix the triple-quoted string literal,
so that I can run `code/dictionaries.py`.

## Error report
```
<fakpath>/sysbot/code/dictionaries.py", line 89
    
    ^
SyntaxError: EOF while scanning triple-quoted string literal
```

### Update [Required]
- [ ] Update `code/dictionaries.py`

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.1 hours

**Comment by ramitsawhney27** [comment]
@sammy1997 please look into this

**Comment by sammy1997** [comment]
@bhawesh96 do you want to work on this?
