### ISSUE TITLE
Fix Errors encountered while running the bot.

### ISSUE THREAD

**Issue by CleverFool77** [systers/sysbot#177]
## Description
As a developer,
I need to fix the errors encountered while running the bot
so that I can make changes and work on it .

### Update [Required]
- [ ] Comment `"""` wasn't closed in dictionaries.py ,thus it commented whole `dictionaries.py` file.
- [ ] While running project, it gave `encoding error` as the encoding line wasn't being recognised.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.15 hours

**Comment by sammy1997** [comment]
@CleverFool77 Please be more specific about what the errors are that you are facing?

**Comment by sammy1997** [comment]
@CleverFool77 Can you update the issue with these points?

**Comment by CleverFool77** [comment]
sure :+1:

**Comment by sammy1997** [comment]
@CleverFool77 Do you want to work on this? I will assign this to you in that case.

**Comment by CleverFool77** [comment]
Yes I would like to work on this @sammy1997
