### ISSUE TITLE
[Backlog]Add template files for credentials.

### ISSUE THREAD

**Issue by sara-02** [systers/sysbot#18]
## Description
As a contributor
I need access to the `key-value` stored in the `auth_credentials.py` and the `request_urls.py`,
so that I can test the system locally.

Since both these files contain credentials, we cannot commit them. At the same time we need to provide a `auth_credentials.py.template` and a `request_urls.py.template` file with the keys specified. So that any newcomer can create the respective `auth_credentials.py` and the `reuqest_urls.py` and fill in with his/her own credentials to test locally. We also need to specify how to obtain those credentials. This will also make the review process easier, as we will know which files the credentials are being picked from.

## Mocks
auth_credentials.py.template
```
import os
key1=os.environ.get("key1","default_value")
```
README
`Goto <link> and get your credentials/tokens`
`cp auth_credentials.py.template auth_credentials.py`

## Acceptance Criteria
Add the template files and update the `README` as to how to generate populate the credentials, and obtain a non-template credentials file.

### Update [Required]
- [ ] README.md
- [ ] auth_credentials.py.template
- [ ] request_urls.py.template

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 mins

**Comment by ramitsawhney27** [comment]
Seems valid as per our discussion on Slack, @sammy1997 can start working on this.

**Comment by sammy1997** [comment]
@sara-02  @ramitsawhney27 Is this valid? Because one we won't get the key from the environment, and two the accessibility of the credentials is still a point of concern( as to how it is to be shared ).

**Comment by sara-02** [comment]
@sammy1997 Yes the accessibility part is a concern. Irrespective of that, it is a good practice to store the credentials in a `.env` file and load them in your config file. That way you will never be committing them. We can put this issue on the backlog for the time being, until we finalize an approach.

**Comment by sammy1997** [comment]
Keeping #88 in mind this one can be closed. Thanks @sara-02 .
