### ISSUE TITLE
Invitation to newcomers team

### ISSUE THREAD

**Issue by ramitsawhney27** [systers/sysbot#28]
## Description
As a user
I need Sysbot to invite new joiners to the newcomers' team via a slash command.

### Update [Required]
- [ ] Add functionality to invite necomers to newcomers team via a slash command: /sysbot invite

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by sara-02** [comment]
@ramitsawhney27 I have a doubt here, how is this issue different from #7? Seems like a duplicate to me 
:confused:

**Comment by ramitsawhney27** [comment]
@sara-02 This basically adds the functionality to invite a user into a particular “Slack team” called newcomers whereas issue #7 adds the functionality so that Sysbot can explain formats of how users can interact with Sysbot in the future. Both are triggered by the same event, however, they’re performing different tasks. We broke issues down so we can have more indepedent cohesive modules.
