### ISSUE TITLE
Claiming issues from Github

### ISSUE THREAD

**Issue by ramitsawhney27** [systers/sysbot#42]
## Description
As a user
I need to claim issues from github
so that I can automate issue claiming.

### Update [Required]
- [ ] Add functionality to claim an issue from Github.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by sammy1997** [comment]
@ramitsawhney27 This has been done. Please merge the PR.
