### ISSUE TITLE
Cleaning up labels

### ISSUE THREAD

**Issue by ramitsawhney27** [systers/sysbot#45]
## Description
As a mentor,
I need all old PRs and issues to have their tags changed/updated properly
so that I can have easier access and correct labels.

### Update [Required]
- [ ] [Update tags for all issues and PRs]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by sammy1997** [comment]
@ramitsawhney27 If I want to do this via the bot, I will need write access to all repositories. This has to be discussed with the admins and community. Also, I would like to complete the documentation and remaining issues for Sysbot first, and then work on code clean up if that's fine?

**Comment by ramitsawhney27** [comment]
As of now, I was thinking of getting this done manually, not via the bot.
Sure, lets do it towards the end.

**Comment by sammy1997** [comment]
Closing this issue. I have updated the labels.
