### ISSUE TITLE
Design for Template recognition

### ISSUE THREAD

**Issue by ramitsawhney27** [systers/sysbot#48]
## Description
As a user,
I need to create a design for issue template recognition,
so that I can ensure proper formatting for issue creation is followed.

### Update [Required]
- [ ] Create an appropriate template for issue creation formatting checking.
- [ ] Take in more suggestions from the community to finalize.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
Will be finalized after the design is solidified post community discussions.

**Comment by sammy1997** [comment]
Done @ramitsawhney27 . Please review the doc on Slack.

**Comment by ramitsawhney27** [comment]
@sammy1997 seems fine. Can you send it as a PR so we can include it in the repo, later we can modify it whenever we're checking for the format.

**Comment by sammy1997** [comment]
Ok. @ramitsawhney27 Do you want it as a doc in the repo?
