### ISSUE TITLE
Add a slash command for helping users get a list of available commands with the bot 

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#52]
## Description
As a developer,
I need to add a /sysbot_help command,
so that users can get a list of all the commands that are used available with Sysbot.

### Update [Required]
- [ ] Add a /sysbot_help command that responds with list of available commands

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by ramitsawhney27** [comment]
Seems fine, you can send a PR for this whenever!
