### ISSUE TITLE
Create API Documentaion

### ISSUE THREAD

**Issue by sara-02** [systers/sysbot#54]
## Description
As a contributor/consumer of the Sysbot,
I need access to the API Documentation,
so that I can know the existing functionalities of the bot and how to use them.

### Update [Required]
- [ ] Add a Swagger File
- [ ] Add a detailed API fucntionality and usage doc( A function description Markdown file)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
12 hours

**Comment by sammy1997** [comment]
@sara-02 I think this can be closed

**Comment by sammy1997** [comment]
@sara-02 Closing this issue as per our discussions with @prachi1210 .
