### ISSUE TITLE
Ephimeral messages instead of public ones

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#59]
## Description
As a developer,
I need send messages from the bot to channels,
such that it's only visible to the command user and not publicly.

## Mocks
![ephimeral](https://user-images.githubusercontent.com/24635701/41146298-831be704-6b20-11e8-907d-034afb3b42b6.png)

### Update [Required]
- [ ] Remove public commenting, and add ephimeral messages
### Enhancement to Update [Optional]
- [ ] Make the messages more informative based on the commands

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
1 hour

**Comment by prachi1210** [comment]
Approved
