### ISSUE TITLE
Add un-assign and un-claim commands on github

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#61]
## Description
As a developer,
I need add an unclaim and unassign commands to sysbots ability on github.

### Update [Required]
- [ ] Add unassign and unclaim commands on github

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1.5 hours

**Comment by ramitsawhney27** [comment]
Approved.
