### ISSUE TITLE
Amend approve issue feature to disallow author of issue from approving an issue

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#62]
## Description
As a developer,
I need to amend the feature to approve issues,
so that author of the issue can't approve it.

### Update [Required]
- [ ] Amend approve issue feature to disallow author of issue from approving an issue.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by ramitsawhney27** [comment]
Approved
