### ISSUE TITLE
Take github profile info from slack for claim sash command

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#66]
## Description
As a developer,
I need take the GitHub profile info from Slack,
so that the user does not need to mention it.

### Update [Required]
- [ ] Slash command should take GitHub profile info from the Slack profile for the claim command

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
0.5 hours

**Comment by sammy1997** [comment]
@sara-02 @ramitsawhney27 @Akshitaag Please review this. I will send a PR for the patch.

**Comment by sara-02** [comment]
@sammy1997 Approved. One question, are we making this an optional or a compulsory check?
I think we should keep both.
Eg `sysbot/claim repo_name issue_number my_github_id` and `sysbot/claim repo_name issue_number` both should be valid  combinations.  @ramitsawhney27 @Akshitaag  what are your thoughts?

**Comment by ramitsawhney27** [comment]
Yeah, I agree with Sara here. Lets keep both options.
