### ISSUE TITLE
Add check against claiming or assigning un-approved issues

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#68]
## Description
As a developer,
I need to add a check,
so that un-approved issues can't be claimed or assigned.

## Mocks
![unapproved_issue_assigned](https://user-images.githubusercontent.com/24635701/41345541-9f43a156-6f21-11e8-8675-6e5a2738bf98.png)

### Update [Required]
- [ ] Add a check so that un-approved issues can't be claimed or assigned

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by sammy1997** [comment]
@sara-02 @ramitsawhney27 @Akshitaag Please approve this

**Comment by sara-02** [comment]
@sammy1997 Thanks for adding this. I approve this, please send a PR.

**Comment by ramitsawhney27** [comment]
Approved.
