### ISSUE TITLE
List all mentors/maintainers for an issue

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#71]
## Description
As a developer,
I need to add a slash command,
so that Sysbot can list all the mentor/maintainers/contributors for a project based on the argument passed or on the channel on which it was called in.

## Mocks
-N.A.-

### Update [Required]
- [ ] Add slash command to list all mentor/maintainers/contributors

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by sammy1997** [comment]
@sara-02 @ramitsawhney27 @Akshitaag Please review this one.

**Comment by sara-02** [comment]
@sammy1997 do we really want to list all the contributors? That will be a long list.
One more question are we going to list only the name of the mentors or their slack ids as well?

**Comment by ramitsawhney27** [comment]
Closing this for now based on our discussion. Once Slack teams are added we will use that and create a new issue.
