### ISSUE TITLE
Close PR if it is sent to unapproved issues

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#72]
## Description
As a developer,
I need to check the PR body,
so that the bot can close the PR if it is sent to un-approved issues, and close it if it does.

### Update [Required]
- [ ] Check if PR if it is sent to un-approved issues, and close it if it does

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by sara-02** [comment]
@sammy1997 A subset of this would be to close the PR if no `Fixes #<issue_nu>` is found in the PR template body. Will you be creating a separate issue for it?

**Comment by sammy1997** [comment]
Yes @sara-02. That will be checked under the issue of template checking.
