### ISSUE TITLE
Refactoring the code 

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#75]
## Description
As a developer,
I need to refactor the code,
so that the files can be arranged better.

### Update [Required]
- [ ] Refactor the code and ensure everything works well!

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15 mins

**Comment by sammy1997** [comment]
@sara-02 @ramitsawhney27 @Akshitaag Please review this.

**Comment by sara-02** [comment]
:+1:  You may change the label and start working on it :)

**Comment by ramitsawhney27** [comment]
Approved, go ahead.
