### ISSUE TITLE
Check if issues match provided template

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#76]
## Description
As a developer,
I need to add a check on new issues,
so that the bot will label template mismatched issues.

## Mocks
-N.A.-

### Update [Required]
- [ ] The bot should label issues that don't follow the templates with 'Template Mismatch' label.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by sara-02** [comment]
@sammy1997 thanks, approving this issue. You can change the label and start working on it.

**Comment by ramitsawhney27** [comment]
Approved, go ahead.
