### ISSUE TITLE
Patch for return values of Slack and Github functions for testing

### ISSUE THREAD

**Issue by sammy1997** [systers/sysbot#85]
## Description
As a developer,
I need send a patch,
so that each Slack/GitHub function can return a message/status so that they can be unit tested.

## Mocks
-N.A-

### Update [Required]
- [ ] All the functions should atleast return the status code for the process.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by sammy1997** [comment]
@ramitsawhney27 @Akshitaag @sara-02 Please approve this. I will send a PR for the same. This is as discussed in the weekly meet. @sara-02 , you can read the meeting minutes for more details

**Comment by ramitsawhney27** [comment]
Go ahead.
